#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
module: Problem 2
author: Zach Lamberty
created: 2014-02-13

Description:
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
"""

def fibGen(fibMax):
    a, b = 0, 1
    yield a
    yield b
    while b <= fibMax:
        a, b = b, a + b
        yield b


if __name__ == '__main__':

    print sum(el for el in fibGen(4000000) if not el % 2)

